### ISSUE TITLE
CTF past and present contest

### ISSUE THREAD

**Issue by arnabsen1729** [codeiiest-dev/CTFBot#5]
Adding a command `!ctf running` to display the running contests
Adding a command `!ctf past` to display the past contests. (preferably the last one)

**Comment by Rajdeep-G** [comment]
I want to work on this....Please assign this to me.

**Comment by arnabsen1729** [comment]
Sure!, It will just be a modification of the future function, Won't take much time I suppose ;)

**Comment by arnabsen1729** [comment]
@sadn1ck just check it once, looks good to me

**Comment by berakrishnendu36** [comment]
I want to fix the !running part..

**Comment by sadn1ck** [comment]
Fixed, gj peeps.
